(()=>{
let used=false,active=false,target=null;
const net=()=>window.FRESH_NET;
const side=()=>net()?.seat==='joiner'?'top':'bottom';
const phase=()=>side()==='top'?'topMove':'bottomMove';
const energy=()=>side()==='top'?Number(window.opponentEnergy):Number(window.localEnergy);
const node=()=>side()==='top'?window.opponentPaddleNode:window.localPaddleNode;
function refresh(){const b=document.getElementById('mathieuP1');if(!b)return;b.disabled=used;b.classList.toggle('used',used);}
function sync(st){const p=st?.characterPowers?.[side()]?.mathieu_energy_only;if(p){used=!!p.used;active=!!p.active;}refresh();}
function addUI(){
 const style=document.createElement('style');style.textContent=`#mathieuCard{position:fixed;left:14px;bottom:14px;z-index:12000;width:96px;display:none;transition:.18s;background:#e7b51d;border:3px solid #111;border-radius:10px;padding:7px;color:#111;font-family:Arial,sans-serif;box-shadow:0 5px 15px #0008}body.fresh-game-ready #mathieuCard{display:block}#mathieuCard:hover{width:230px}#mathieuCard h3{margin:0 0 5px;text-align:center;font-size:14px}#mathieuP1{width:100%;min-height:55px;border:2px solid #111;border-radius:7px;background:#fff9;font-weight:800;cursor:pointer}#mathieuP1.used{opacity:.4;cursor:not-allowed}.charModal{position:fixed;inset:0;z-index:16000;display:none;align-items:center;justify-content:center;background:#0009}.charModal.open{display:flex}.charBox{width:min(470px,90vw);background:#171717;color:#fff;border:2px solid #e7b51d;border-radius:16px;padding:22px;font-family:Arial,sans-serif}.charBtns{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.charBtns button{padding:10px 16px;border:0;border-radius:8px;font-weight:700;cursor:pointer}.charBtns button:disabled{opacity:.4}`;document.head.appendChild(style);
 const card=document.createElement('div');card.id='mathieuCard';card.innerHTML='<h3>MATHIEU LIVAIN</h3><button id="mathieuP1">1 — Déplacement : Énergie uniquement</button>';document.body.appendChild(card);
 const c=document.createElement('div');c.id='mathieuConfirm';c.className='charModal';c.innerHTML='<div class="charBox"><h2>Mathieu — Pouvoir 1</h2><p><b>Déplacement : Énergie uniquement</b></p><p>Pour ce déplacement, toute la distance est payée avec de l’Énergie. Aucun point de Déplacement n’est dépensé.</p><div class="charBtns"><button data-close>Annuler</button><button id="mathieuValidate">Valider</button></div></div>';document.body.appendChild(c);
 const a=document.createElement('div');a.id='mathieuApply';a.className='charModal';a.innerHTML='<div class="charBox"><h2>Appliquer le pouvoir</h2><p id="mathieuApplyText"></p><div class="charBtns"><button data-close>Annuler</button><button id="mathieuApplyBtn">Appliquer</button></div></div>';document.body.appendChild(a);
 document.querySelectorAll('.charModal [data-close]').forEach(b=>b.onclick=()=>b.closest('.charModal').classList.remove('open'));
 document.getElementById('mathieuP1').onclick=()=>{if(used)return;if(window.phase!==phase()){alert('Ce pouvoir s’utilise au moment du déplacement de votre raquette.');return;}target=side()==='top'?window.pendingMoveTarget:window.freshBottomMoveTarget;if(target==null){alert('Aucun déplacement n’est actuellement en attente.');return;}c.classList.add('open');};
 document.getElementById('mathieuValidate').onclick=()=>{c.classList.remove('open');const d=window.shortestDistance(node(),Number(target)),e=energy();document.getElementById('mathieuApplyText').textContent=`Distance : ${d} — coût : ${d} Énergie — Énergie disponible : ${e}.`;document.getElementById('mathieuApplyBtn').disabled=d>e;a.classList.add('open');};
 document.getElementById('mathieuApplyBtn').onclick=()=>{a.classList.remove('open');net()?.socket.emit('freshActivateCharacterPower',{room:net().room,power:'mathieu_energy_only'});};refresh();
}
function wrapMoves(){
 const top=window.openMoveAllocation;if(typeof top==='function')window.openMoveAllocation=function(v){if(!(active&&side()==='top'))return top(v);window.pendingMoveTarget=v;const d=window.shortestDistance(window.opponentPaddleNode,v),m=document.getElementById('moveModal'),s=document.getElementById('moveSubtitle'),ch=document.getElementById('moveChoices'),z=document.getElementById('zeroMoveTopContinue');s.textContent=`Mathieu — distance ${d} : ${d} Énergie, 0 Déplacement`;ch.innerHTML='';if(z)z.classList.remove('show');const b=document.createElement('button');b.className='moveChoice';b.textContent=`0 déplacement + ${d} énergie`;b.disabled=d>Number(window.opponentEnergy);ch.appendChild(b);m.classList.add('open');m.setAttribute('aria-hidden','false');};
 const bottom=window.openLocalMoveAllocation;if(typeof bottom==='function')window.openLocalMoveAllocation=function(v){if(!(active&&side()==='bottom'))return bottom(v);const d=window.shortestDistance(window.localPaddleNode,v),m=document.getElementById('localMoveModal'),s=document.getElementById('localMoveSubtitle'),ch=document.getElementById('localMoveChoices'),z=document.getElementById('zeroMoveBottomContinue');s.textContent=`Mathieu — distance ${d} : ${d} Énergie, 0 Déplacement`;ch.innerHTML='';if(z)z.classList.remove('show');const b=document.createElement('button');b.className='moveChoice';b.textContent=`0 déplacement + ${d} énergie`;b.disabled=d>Number(window.localEnergy);ch.appendChild(b);m.classList.add('open');m.setAttribute('aria-hidden','false');};
}
window.addEventListener('load',()=>{addUI();wrapMoves();const s=net()?.socket;if(!s)return;['roomReady','freshNextPoint','freshTopMoveApplied','freshBottomMoveApplied'].forEach(ev=>s.on(ev,p=>p?.state&&sync(p.state)));s.on('freshCharacterPowerActivated',p=>{if(!p?.state)return;sync(p.state);if(p.side!==side())return;active=true;setTimeout(()=>side()==='top'?window.openMoveAllocation(target):window.openLocalMoveAllocation(target),0);});});
})();