(()=>{
let used=false,active=false,target=null,lastState=null;
const net=()=>window.FRESH_NET, side=()=>net()?.seat==='joiner'?'top':'bottom';
const energy=()=>side()==='top'?Number(lastState?.opponentEnergy):Number(lastState?.localEnergy);
const node=()=>side()==='top'?(lastState?.opponentPaddleNode??'S'):(lastState?.localPaddleNode??'S');
function refresh(){const b=document.getElementById('mathieuP1'),r=document.querySelector('.mathieuFace.recto');if(b){b.classList.toggle('used',used);b.setAttribute('aria-disabled',used?'true':'false');}if(r)r.classList.toggle('afterP1',used);}
function sync(st){lastState=st;const p=st?.characterPowers?.[side()]?.mathieu_energy_only;if(p){used=!!p.used;active=!!p.active;}refresh();}
function moveModalOpen(){const id=side()==='top'?'moveModal':'localMoveModal',m=document.getElementById(id);return !!m&&(m.classList.contains('open')||m.getAttribute('aria-hidden')==='false');}
function currentTarget(){const candidates=[lastState?.lastPlayedValue,window.pendingMoveTarget,window.freshBottomMoveTarget];for(const v of candidates){const n=Number(v);if(n>=1&&n<=6)return n;}return null;}
function lockJournalAndCards(){
 const cards=document.getElementById('mathieuCards'); if(!cards)return;
 const old=document.getElementById('freshBotJournal'); if(old)old.style.setProperty('display','none','important');
 const journal=document.getElementById('freshMatchJournal');
 if(journal){
  journal.style.setProperty('left','14px','important');journal.style.setProperty('top','14px','important');
  journal.style.setProperty('width','364px','important');journal.style.setProperty('height','112px','important');journal.style.setProperty('max-height','112px','important');journal.style.setProperty('min-height','0','important');
  journal.style.setProperty('overflow','hidden','important');journal.style.setProperty('transform','none','important');journal.style.setProperty('box-sizing','border-box','important');
  const lines=document.getElementById('freshMatchJournalLines');if(lines){lines.style.setProperty('max-height','54px','important');lines.style.setProperty('overflow-y','auto','important');}
  const r=journal.getBoundingClientRect();cards.style.left=`${Math.max(70,r.left+58)}px`;cards.style.top=`${r.bottom+105}px`;cards.style.bottom='auto';
 }else{cards.style.left='70px';cards.style.top='231px';cards.style.bottom='auto';}
}
function addUI(){
 const st=document.createElement('style');st.textContent=`#freshBotJournal{display:none!important}#mathieuCards{position:fixed;left:70px;top:231px;z-index:12000;display:none;width:620px;height:300px;font-family:Arial,sans-serif;filter:drop-shadow(0 5px 10px #0007);overflow:visible}body.fresh-game-ready #mathieuCards{display:block}.mathieuFace{position:absolute;width:162px;top:0;transition:transform .2s ease;transform-origin:center center;overflow:visible}.mathieuFace img{display:block;width:100%;height:auto;border-radius:8px;pointer-events:none}.mathieuFace.verso{left:0;z-index:1}.mathieuFace.recto{left:350px;z-index:2;transform:rotate(0deg)}.mathieuFace.verso:hover{transform:scale(1.5);z-index:12030}.mathieuFace.recto:hover{transform:scale(1.5);z-index:12030}.mathieuFace.recto.afterP1{transform:rotate(-90deg)}.mathieuFace.recto.afterP1:hover{transform:rotate(-90deg) scale(1.5);z-index:12030}#mathieuP1{position:absolute;left:4.5%;top:23%;width:43.5%;height:31%;border:0;background:transparent;cursor:pointer;border-radius:5px;padding:0}#mathieuP1:hover{outline:3px solid rgba(255,255,255,.9);background:rgba(255,255,255,.10)}#mathieuP1.used{cursor:not-allowed;background:rgba(0,0,0,.38);outline:2px solid rgba(0,0,0,.55)}#mathieuP1.used:after{content:'UTILISÉ';position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:900;font-size:12px;text-shadow:0 1px 3px #000;transform:rotate(-12deg)}.charModal{position:fixed;inset:0;z-index:16000;display:none;align-items:center;justify-content:center;background:#0009}.charModal.open{display:flex}.charBox{width:min(470px,90vw);background:#171717;color:#fff;border:2px solid #e7b51d;border-radius:16px;padding:22px;font-family:Arial,sans-serif}.charBtns{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.charBtns button{padding:10px 16px;border:0;border-radius:8px;font-weight:700;cursor:pointer}.charBtns button:disabled{opacity:.4}`;document.head.appendChild(st);
 document.body.insertAdjacentHTML('beforeend','<div id="mathieuCards"><div class="mathieuFace verso" title="Mathieu Livain — verso"><img src="/mathieu_verso.png" alt="Mathieu Livain — verso"></div><div class="mathieuFace recto" title="Survolez pour agrandir"><img src="/mathieu_recto.png" alt="Mathieu Livain — pouvoirs"><button id="mathieuP1" type="button" aria-label="Pouvoir 1 de Mathieu"></button></div></div><div id="mathieuConfirm" class="charModal"><div class="charBox"><h2>Mathieu — Pouvoir 1</h2><p><b>Déplacement : Énergie uniquement</b></p><p>Toute la distance est payée avec de l’Énergie. Aucun point de Déplacement n’est dépensé.</p><div class="charBtns"><button data-close>Annuler</button><button id="mathieuValidate">Valider</button></div></div></div><div id="mathieuApply" class="charModal"><div class="charBox"><h2>Appliquer le pouvoir</h2><p id="mathieuApplyText"></p><div class="charBtns"><button data-close>Annuler</button><button id="mathieuApplyBtn">Appliquer</button></div></div></div>');
 document.querySelectorAll('.charModal [data-close]').forEach(b=>b.onclick=()=>b.closest('.charModal').classList.remove('open'));
 const confirm=document.getElementById('mathieuConfirm'),apply=document.getElementById('mathieuApply');
 document.getElementById('mathieuP1').onclick=()=>{if(used)return;if(!moveModalOpen()){alert('Ce pouvoir s’utilise au moment du déplacement de votre raquette.');return;}target=currentTarget();if(!target){alert('Aucun déplacement en attente.');return;}confirm.classList.add('open');};
 document.getElementById('mathieuValidate').onclick=()=>{confirm.classList.remove('open');const d=window.shortestDistance(node(),target),e=energy();document.getElementById('mathieuApplyText').textContent=`Distance : ${d} — coût : ${d} Énergie — Énergie disponible : ${e}.`;document.getElementById('mathieuApplyBtn').disabled=d>e;apply.classList.add('open');};
 document.getElementById('mathieuApplyBtn').onclick=()=>{apply.classList.remove('open');net()?.socket.emit('freshActivateCharacterPower',{room:net().room,power:'mathieu_energy_only'});};refresh();requestAnimationFrame(()=>{lockJournalAndCards();setTimeout(lockJournalAndCards,300);});
}
function powerMove(v,isTop){const d=window.shortestDistance(isTop?(lastState?.opponentPaddleNode??'S'):(lastState?.localPaddleNode??'S'),v),m=document.getElementById(isTop?'moveModal':'localMoveModal'),sub=document.getElementById(isTop?'moveSubtitle':'localMoveSubtitle'),ch=document.getElementById(isTop?'moveChoices':'localMoveChoices'),z=document.getElementById(isTop?'zeroMoveTopContinue':'zeroMoveBottomContinue');sub.textContent=`Mathieu — distance ${d} : ${d} Énergie, 0 Déplacement`;ch.innerHTML='';if(z)z.classList.remove('show');const b=document.createElement('button');b.className='moveChoice';b.textContent=`0 déplacement + ${d} énergie`;b.disabled=d>energy();ch.appendChild(b);m.classList.add('open');m.setAttribute('aria-hidden','false');}
function wrap(){const t=window.openMoveAllocation,b=window.openLocalMoveAllocation;if(typeof t==='function')window.openMoveAllocation=v=>active&&side()==='top'?powerMove(v,true):t(v);if(typeof b==='function')window.openLocalMoveAllocation=v=>active&&side()==='bottom'?powerMove(v,false):b(v);}
window.addEventListener('load',()=>{addUI();wrap();window.addEventListener('resize',lockJournalAndCards);const s=net()?.socket;if(!s)return;['roomReady','freshNextPoint','freshTopMoveApplied','freshBottomMoveApplied'].forEach(ev=>s.on(ev,p=>{if(p?.state)sync(p.state);setTimeout(lockJournalAndCards,0);}));s.on('freshCharacterPowerActivated',p=>{if(!p?.state)return;sync(p.state);if(p.side!==side())return;active=true;target=Number(p.state.lastPlayedValue);setTimeout(()=>side()==='top'?window.openMoveAllocation(target):window.openLocalMoveAllocation(target),0);});});
})();