(()=>{
let lastState=null,used=false,active=false;
const net=()=>window.FRESH_NET;
const side=()=>net()?.seat==='joiner'?'top':'bottom';
function button(){return document.getElementById('jeanneP1Main');}
function choiceOpen(){return !!document.getElementById('valueModal')?.classList.contains('open')||!!document.getElementById('responseModal')?.classList.contains('open');}
function refreshCosts(){if(!active)return;const response=document.getElementById('responseValues'),value=document.getElementById('valueButtons');const root=response&&response.querySelector('button.responseChoice')?response:value;if(!root)return;const sub=(response&&response.querySelector('button.responseChoice'))?document.getElementById('responseSubtitle'):document.getElementById('valueSubtitle');if(!sub)return;const m=(sub.textContent||'').match(/(?:tuile imprimée|Valeur imprimée)\s*:\s*([1-6])/i);if(!m)return;const printed=Number(m[1]);for(const b of root.querySelectorAll('button.responseChoice,button.valueChoice')){const v=Number(b.dataset.value||((b.textContent||'').match(/^\s*([1-6])/)||[])[1]);if(!v)continue;const small=b.querySelector('small');if(!small||/Réponse interdite/i.test(small.textContent||''))continue;const cost=Math.max(0,Math.abs(v-printed)-1);small.textContent=`Coût : ${cost} énergie${cost>1?'s':''}`;if(b.classList.contains('responseChoice')){const energy=side()==='top'?Number(lastState?.opponentEnergy):Number(lastState?.localEnergy);b.disabled=cost>energy;}}}
function refresh(){const b=button(),r=document.querySelector('#characterDisplayCards .characterDisplayFace.recto');if(!b||!r)return;const mine=document.body.dataset.pingCharacter==='jeanne';let allowed=false;if(lastState&&!lastState.pointEnded){const me=side();allowed=(lastState.phase==='service'&&lastState.pointServerSide===me)||lastState.phase===(me==='top'?'topResponse':'bottomResponse');}const usable=mine&&allowed&&choiceOpen()&&!used;b.style.display=mine?'block':'none';b.disabled=!usable;b.classList.toggle('used',used);r.classList.toggle('jeanneUnavailable',mine&&!usable);}
function sync(st){if(!st)return;lastState=st;const p=st.characterPowers?.[side()]?.jeanne_pm1;if(p){used=!!p.used;active=!!p.active;}refresh();if(active){refreshCosts();requestAnimationFrame(refreshCosts);}}
function init(){const face=document.querySelector('#characterDisplayCards .characterDisplayFace.recto');if(!face||button())return;const css=document.createElement('style');css.textContent=`#jeanneP1Main{position:absolute;left:2.5%;top:2.5%;width:46%;height:45%;border:0;background:transparent;cursor:pointer;border-radius:5px;padding:0;z-index:6}#jeanneP1Main:hover:not(:disabled){outline:3px solid rgba(255,255,255,.9);background:rgba(255,255,255,.10)}#jeanneP1Main.used{cursor:not-allowed;background:rgba(0,0,0,.38);outline:2px solid rgba(0,0,0,.55)}#jeanneP1Main.used:after{content:'UTILISÉ';position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:900;font-size:12px;text-shadow:0 1px 3px #000;transform:rotate(-12deg)}.characterDisplayFace.recto.jeanneUnavailable{filter:grayscale(1) brightness(.55)}.jeannePModal{position:fixed;inset:0;z-index:16000;display:none;align-items:center;justify-content:center;background:#0009}.jeannePModal.open{display:flex}.jeannePBox{width:min(470px,90vw);background:#171717;color:#fff;border:2px solid #e7b51d;border-radius:16px;padding:22px;font-family:Arial,sans-serif}.jeannePBtns{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.jeannePBtns button{padding:10px 16px;border:0;border-radius:8px;font-weight:700;cursor:pointer}`;document.head.appendChild(css);face.insertAdjacentHTML('beforeend','<button id="jeanneP1Main" title="Jeanne — Pouvoir 1"></button>');document.body.insertAdjacentHTML('beforeend','<div id="jeanneP1Confirm" class="jeannePModal"><div class="jeannePBox"><h2>Jeanne — Pouvoir 1</h2><p><b>Modification ±1 gratuite</b></p><p>Modifiez gratuitement de 1 la valeur de la tuile que vous allez jouer.</p><div class="jeannePBtns"><button data-close>Annuler</button><button id="jeanneP1Validate">Valider</button></div></div></div>');const modal=document.getElementById('jeanneP1Confirm');modal.querySelector('[data-close]').onclick=()=>modal.classList.remove('open');button().onclick=()=>{if(!button().disabled)modal.classList.add('open');};document.getElementById('jeanneP1Validate').onclick=()=>{modal.classList.remove('open');net()?.socket.emit('freshActivateJeannePower',{room:net().room,power:'jeanne_pm1'});};setInterval(refresh,150);const s=net()?.socket;if(!s)return;if(typeof s.onAny==='function')s.onAny((ev,p)=>{if(p?.state)sync(p.state);});s.on('freshJeannePowerActivated',p=>{if(!p?.state)return;sync(p.state);if(p.side===side()&&p.power==='jeanne_pm1'){active=true;refreshCosts();requestAnimationFrame(refreshCosts);setTimeout(refreshCosts,0);}});}
window.addEventListener('load',init);
})();