(()=>{
let lastState=null,used=false,active=false,target=null;
const net=()=>window.FRESH_NET;
const side=()=>net()?.seat==='joiner'?'top':'bottom';
const energy=()=>side()==='top'?Number(lastState?.opponentEnergy):Number(lastState?.localEnergy);
const node=()=>side()==='top'?(lastState?.opponentPaddleNode??'S'):(lastState?.localPaddleNode??'S');
function moveModalOpen(){const m=document.getElementById(side()==='top'?'moveModal':'localMoveModal');return !!m&&(m.classList.contains('open')||m.getAttribute('aria-hidden')==='false');}
function currentTarget(){for(const v of [lastState?.lastPlayedValue,window.pendingMoveTarget,window.freshBottomMoveTarget]){const n=Number(v);if(n>=1&&n<=6)return n;}return null;}
function button(){return document.getElementById('mathieuP1Main');}
function refresh(){const b=button(),r=document.querySelector('#characterDisplayCards .characterDisplayFace.recto');if(!b||!r)return;const mine=document.body.dataset.pingCharacter==='mathieu',usable=mine&&moveModalOpen()&&!used;b.style.display=mine?'block':'none';b.disabled=!usable;b.classList.toggle('used',used);r.classList.toggle('mathieuUnavailable',mine&&!usable);}
function sync(st){if(!st)return;lastState=st;const p=st.characterPowers?.[side()]?.mathieu_energy_only;if(p){used=!!p.used;active=!!p.active;}refresh();}
function addUI(){const face=document.querySelector('#characterDisplayCards .characterDisplayFace.recto');if(!face||button())return;face.style.overflow='visible';const st=document.createElement('style');st.textContent=`#mathieuP1Main{position:absolute;left:2.5%;top:2.5%;width:46%;height:45%;border:0;background:transparent;cursor:pointer;border-radius:5px;padding:0;z-index:5}#mathieuP1Main:hover:not(:disabled){outline:3px solid rgba(255,255,255,.9);background:rgba(255,255,255,.10)}#mathieuP1Main.used{cursor:not-allowed;background:rgba(0,0,0,.38);outline:2px solid rgba(0,0,0,.55)}#mathieuP1Main.used:after{content:'UTILISÉ';position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:900;font-size:12px;text-shadow:0 1px 3px #000;transform:rotate(-12deg)}.characterDisplayFace.recto.mathieuUnavailable{filter:grayscale(1) brightness(.55)}.mathieuModal{position:fixed;inset:0;z-index:16000;display:none;align-items:center;justify-content:center;background:#0009}.mathieuModal.open{display:flex}.mathieuBox{width:min(470px,90vw);background:#171717;color:#fff;border:2px solid #e7b51d;border-radius:16px;padding:22px;font-family:Arial,sans-serif}.mathieuBtns{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.mathieuBtns button{padding:10px 16px;border:0;border-radius:8px;font-weight:700;cursor:pointer}`;document.head.appendChild(st);face.insertAdjacentHTML('beforeend','<button id="mathieuP1Main" title="Mathieu — Pouvoir 1"></button>');document.body.insertAdjacentHTML('beforeend','<div id="mathieuP1Confirm" class="mathieuModal"><div class="mathieuBox"><h2>Mathieu — Pouvoir 1</h2><p><b>Déplacement : Énergie uniquement</b></p><p>Toute la distance est payée avec de l’Énergie. Aucun point de Déplacement n’est dépensé.</p><div class="mathieuBtns"><button data-close>Annuler</button><button id="mathieuP1Validate">Valider</button></div></div></div>');const modal=document.getElementById('mathieuP1Confirm');modal.querySelector('[data-close]').onclick=()=>modal.classList.remove('open');button().onclick=()=>{if(button().disabled)return;target=currentTarget();if(!target)return;modal.classList.add('open');};document.getElementById('mathieuP1Validate').onclick=()=>{modal.classList.remove('open');net()?.socket.emit('freshActivateCharacterPower',{room:net().room,power:'mathieu_energy_only'});};refresh();}
function powerMove(v,isTop){const raw=window.shortestDistance(isTop?(lastState?.opponentPaddleNode??'S'):(lastState?.localPaddleNode??'S'),v),m=document.getElementById(isTop?'moveModal':'localMoveModal'),sub=document.getElementById(isTop?'moveSubtitle':'localMoveSubtitle'),ch=document.getElementById(isTop?'moveChoices':'localMoveChoices'),z=document.getElementById(isTop?'zeroMoveTopContinue':'zeroMoveBottomContinue');ch.innerHTML='';if(z)z.classList.remove('show');sub.textContent=`Mathieu — distance ${raw} : ${raw} Énergie, 0 Déplacement`;const b=document.createElement('button');b.className='moveChoice';b.textContent=`0 déplacement + ${raw} énergie`;b.disabled=raw>energy();ch.appendChild(b);m.classList.add('open');m.setAttribute('aria-hidden','false');}
function wrap(){const t=window.openMoveAllocation,b=window.openLocalMoveAllocation;if(typeof t==='function')window.openMoveAllocation=v=>active&&side()==='top'?powerMove(v,true):t(v);if(typeof b==='function')window.openLocalMoveAllocation=v=>active&&side()==='bottom'?powerMove(v,false):b(v);}
window.addEventListener('load',()=>{addUI();wrap();setInterval(refresh,150);const s=net()?.socket;if(!s)return;if(typeof s.onAny==='function')s.onAny((ev,p)=>{if(p?.state)sync(p.state);});s.on('freshCharacterPowerActivated',p=>{if(!p?.state)return;sync(p.state);if(p.side!==side()||p.power!=='mathieu_energy_only')return;target=Number(p.state.lastPlayedValue);active=true;setTimeout(()=>side()==='top'?window.openMoveAllocation(target):window.openLocalMoveAllocation(target),0);});});
})();